# 基础镜像
FROM redis:7.0.0
# author
MAINTAINER ix

# 挂载目录
VOLUME /home/ix/redis
# 创建目录
RUN mkdir -p /home/ix/redis
# 指定路径
WORKDIR /home/ix/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/ix/redis/redis.conf
