server:
  port: 8080

# Spring
spring:
  application:
    # 应用名称
    name: ix-gateway
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: ${NACOS_HOST:ix-nacos}:${NACOS_PORT:8848}
        namespace: eeb43899-8a88-4f5b-b0e0-d7c8fd09b86e
      config:
        # 配置中心地址
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        # 配置文件格式
        file-extension: yml
        # 命名空间
        namespace: eeb43899-8a88-4f5b-b0e0-d7c8fd09b86e
        # 配置组
        group: DEFAULT_GROUP
        # shared-configs:
          # - data-id: ix-app-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
    sentinel:
      # nacos配置持久化
      datasource:
        ds:
          # 采用nacos
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            # 命名空间
            namespace: eeb43899-8a88-4f5b-b0e0-d7c8fd09b86e
            dataId: sentinel-ix-gateway
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  config:
    import:
      - optional:nacos:ix-app-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}