# 指定基础镜像
FROM openjdk:17-oracle
LABEL maintainer="zeng_kiku@qq.com"
# 挂载目录
VOLUME /zeng/cloud/ix
# 创建目录
RUN mkdir -p /zeng/cloud/ix
# 指定路径
WORKDIR /zeng/cloud/ix
# 复制jar文件到路径
COPY ./jar/ix-server-system.jar /zeng/cloud/ix/ix-server-system.jar
# 启动网关服务
ENV TZ=Asia/Shanghai JAVA_OPTS="-Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom"
CMD sleep 60; java -jar ix-server-system.jar
