version: '3'
services:
#  ix-nginx:
#    container_name: ix-nginx
#    restart: always
#    image: ix-nginx
#    environment:
#      - TZ=Asia/Shanghai
#    build:
#      context: ./nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/html:/home/ix/ix-ui
#      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/logs:/var/log/nginx
#      - ./nginx/conf.d:/etc/nginx/conf.d
#    depends_on:
#      - ix-gateway
#    links:
#      - ix-gateway
  ix-nacos:
    container_name: ix-nacos
    image: ix-nacos

  ix-gateway:
    container_name: ix-gateway
    image: ix-gateway
    restart: always
    depends_on:
      - ix-nacos
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./ix/gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"

  ix-auth:
    container_name: ix-auth
    image: ix-auth
    restart: always
    depends_on:
      - ix-nacos
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./ix/auth
      dockerfile: dockerfile

  ix-server-system:
    container_name: ix-server-system
    image: ix-server-system
    restart: always
    depends_on:
      - ix-nacos
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    build:
      context: ./ix/server/system
      dockerfile: dockerfile

#  ix-server-job:
#    container_name: ix-server-job
#    image: ix-server-job
#    restart: always
#    depends_on:
#      - ix-nacos
#    environment:
#      - MODE=standalone
#      - TZ=Asia/Shanghai
#    build:
#      context: ./ix/server/job
#      dockerfile: dockerfile
#
#  ix-server-dfs:
#    container_name: ix-server-dfs
#    image: ix-server-dfs
#    restart: always
#    depends_on:
#      - ix-nacos
#    environment:
#      - MODE=standalone
#      - TZ=Asia/Shanghai
#    build:
#      context: ./ix/server/dfs
#      dockerfile: dockerfile
#
#  ix-visual-monitor:
#    container_name: ix-visual-monitor
#    image: ix-visual-monitor
#    restart: always
#    depends_on:
#      - ix-nacos
#    environment:
#      - MODE=standalone
#      - TZ=Asia/Shanghai
#    build:
#      context: ./ix/visual/monitor
#      dockerfile: dockerfile
